/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzashop;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ARUN
 */
public class bill extends javax.swing.JFrame {

     Connection con;
    Statement st;
    String na,em,ad,nu;
    int q;
    float pr=0;
    /** Creates new form bill
     * @throws java.lang.ClassNotFoundException */
    public bill() throws ClassNotFoundException {
        initComponents();
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizzashop","root","1234");
            st= con.createStatement();
         
        } catch (SQLException ex) {
              System.out.println("connectivity failed");
        }
    
         fetchdata();
    }
    public bill(String n,String j,String k,String l,int p) throws ClassNotFoundException
    {
        initComponents();
        seticon();
        na=n;
        ad=j;
        em=k;
        nu=l;
        q=p;
             try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizzashop","root","1234");
            st= con.createStatement();
            
        
        } catch (SQLException ex) {
              System.out.println("connectivity failed");
        }
    
         fetchdata();
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        minimize = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtable1 = new javax.swing.JTable();
        close = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Bill : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 700, 180, 50);

        price.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price.setOpaque(false);
        jPanel1.add(price);
        price.setBounds(900, 700, 220, 50);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jScrollPane1.setOpaque(false);

        billtable.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Price(₹)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billtable.setToolTipText("");
        billtable.setColumnSelectionAllowed(true);
        billtable.setEnabled(false);
        billtable.setGridColor(new java.awt.Color(255, 255, 255));
        billtable.setOpaque(false);
        billtable.setRequestFocusEnabled(false);
        billtable.setRowHeight(50);
        billtable.setShowVerticalLines(false);
        billtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(billtable);
        if (billtable.getColumnModel().getColumnCount() > 0) {
            billtable.getColumnModel().getColumn(0).setResizable(false);
            billtable.getColumnModel().getColumn(1).setResizable(false);
            billtable.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 190, 1080, 480);

        jLabel3.setFont(new java.awt.Font("Death Hector", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thank You For Visiting. Please Come Again");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 820, 1200, 70);

        minimize.setBorder(null);
        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1045, 5, 50, 50);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jScrollPane2.setOpaque(false);

        billtable1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        billtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Price(₹)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billtable1.setToolTipText("");
        billtable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        billtable1.setGridColor(new java.awt.Color(255, 255, 255));
        billtable1.setOpaque(false);
        billtable1.setRequestFocusEnabled(false);
        billtable1.setRowHeight(25);
        billtable1.setShowVerticalLines(false);
        billtable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(billtable1);
        if (billtable1.getColumnModel().getColumnCount() > 0) {
            billtable1.getColumnModel().getColumn(0).setResizable(false);
            billtable1.getColumnModel().getColumn(1).setResizable(false);
            billtable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(390, 190, 410, 480);

        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1120, 0, 50, 50);

        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(0, 0, 140, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/LABEL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 170);

        print.setFont(new java.awt.Font("Just In The Firestorm", 0, 24)); // NOI18N
        print.setText("print ");
        print.setBorder(null);
        print.setBorderPainted(false);
        print.setContentAreaFilled(false);
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(190, 710, 270, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(start.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        try {
            setVisible(false);
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(membership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        try {
            
            setVisible(false);
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(membership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header=new MessageFormat("WAKE AND BAKE");
        MessageFormat footer=new MessageFormat("TOTAL BILL = ₹"+pr );
        try
        {
            billtable1.print(JTable.PrintMode.NORMAL, header, footer);
        }    catch (PrinterException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new bill().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
                
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billtable;
    private javax.swing.JTable billtable1;
    private javax.swing.JButton close;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField price;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables

    private void fetchdata()  {
       JOptionPane.showMessageDialog(null, "These Are your Detail:\nName : "+na+"\nAddress : "+ad+"\nEmail : "+em+"\nContact : "+nu, "CHECK", JOptionPane.QUESTION_MESSAGE);
    
        
        {
        try { 
             try {
                 
                 ResultSet res=st.executeQuery("select * from bill");
                 while(res.next())
                 {
                     pr+=Float.parseFloat(res.getString(4));
                     
                 }
                 
                 float p=(pr*14)/100;
                 st.executeUpdate("insert into bill values('Tax','Service Tax','14%',"+p+")");
                 if(q==10)
                 { p=-(pr*10)/100;
                 st.executeUpdate("insert into bill values('Disc','Membership Discount','10%',"+p+")");
                 }
                 
             } catch (SQLException ex) {
                 Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
             
             }
             if(pr>999)
             {
                 try {
                     st.executeUpdate("insert into bill values('Free','Sundae Strawberry','sundae',0)");
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
             }
             ResultSet res=st.executeQuery("select * from bill");
             billtable.setModel(DbUtils.resultSetToTableModel(res));
             res=st.executeQuery("select * from bill");
             billtable1.setModel(DbUtils.resultSetToTableModel(res));
             res=st.executeQuery("select * from bill");
             pr=0;
             while(res.next())
             {
                 pr+=Float.parseFloat(res.getString(4));
                 
             }price.setText("₹"+pr);

         } catch (SQLException ex) {
             Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
         }
         
        }
       
    }
     private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pizzashop/img/icon.png")));
    }

}
