/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzashop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vipul Rajput
 */
public class burgurs extends javax.swing.JFrame {

    Connection con;
    Statement st;
    /**
     * Creates new form burgurs
     */
    public burgurs() {
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizzashop","root","1234");
            st= con.createStatement();
            
        
        } catch (SQLException ex) {
              System.out.println("connectivity failed");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(burgurs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneerkingmelt = new javax.swing.JRadioButton();
        crispyveg = new javax.swing.JRadioButton();
        tandoorgrill = new javax.swing.JRadioButton();
        vegchillicheesemelt = new javax.swing.JRadioButton();
        veggie = new javax.swing.JRadioButton();
        vegwhopper = new javax.swing.JRadioButton();
        home = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        veggielover = new javax.swing.JButton();
        tandooripaneer = new javax.swing.JButton();
        paneervagorama = new javax.swing.JButton();
        exotica = new javax.swing.JButton();
        countryfest = new javax.swing.JButton();
        veggiesupreme5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        paneerkingmelt.setBorder(null);
        paneerkingmelt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneerkingmelt.setFocusPainted(false);
        paneerkingmelt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paneerkingmelt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        paneerkingmelt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        paneerkingmelt.setOpaque(false);
        paneerkingmelt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        paneerkingmelt.setVerifyInputWhenFocusTarget(false);
        paneerkingmelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneerkingmeltActionPerformed(evt);
            }
        });
        jPanel1.add(paneerkingmelt);
        paneerkingmelt.setBounds(830, 510, 330, 180);

        crispyveg.setBorder(null);
        crispyveg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crispyveg.setFocusPainted(false);
        crispyveg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        crispyveg.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        crispyveg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        crispyveg.setOpaque(false);
        crispyveg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        crispyveg.setVerifyInputWhenFocusTarget(false);
        crispyveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crispyvegActionPerformed(evt);
            }
        });
        jPanel1.add(crispyveg);
        crispyveg.setBounds(440, 180, 330, 180);

        tandoorgrill.setBorder(null);
        tandoorgrill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tandoorgrill.setFocusPainted(false);
        tandoorgrill.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tandoorgrill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tandoorgrill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        tandoorgrill.setOpaque(false);
        tandoorgrill.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        tandoorgrill.setVerifyInputWhenFocusTarget(false);
        tandoorgrill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tandoorgrillActionPerformed(evt);
            }
        });
        jPanel1.add(tandoorgrill);
        tandoorgrill.setBounds(430, 510, 330, 180);

        vegchillicheesemelt.setBorder(null);
        vegchillicheesemelt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vegchillicheesemelt.setFocusPainted(false);
        vegchillicheesemelt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vegchillicheesemelt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        vegchillicheesemelt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        vegchillicheesemelt.setOpaque(false);
        vegchillicheesemelt.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        vegchillicheesemelt.setVerifyInputWhenFocusTarget(false);
        vegchillicheesemelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegchillicheesemeltActionPerformed(evt);
            }
        });
        jPanel1.add(vegchillicheesemelt);
        vegchillicheesemelt.setBounds(50, 510, 330, 180);

        veggie.setBorder(null);
        veggie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        veggie.setFocusPainted(false);
        veggie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        veggie.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        veggie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        veggie.setOpaque(false);
        veggie.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        veggie.setVerifyInputWhenFocusTarget(false);
        veggie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggieActionPerformed(evt);
            }
        });
        jPanel1.add(veggie);
        veggie.setBounds(60, 175, 330, 180);

        vegwhopper.setBorder(null);
        vegwhopper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vegwhopper.setFocusPainted(false);
        vegwhopper.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vegwhopper.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        vegwhopper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        vegwhopper.setOpaque(false);
        vegwhopper.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        vegwhopper.setVerifyInputWhenFocusTarget(false);
        vegwhopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegwhopperActionPerformed(evt);
            }
        });
        jPanel1.add(vegwhopper);
        vegwhopper.setBounds(820, 180, 330, 180);

        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(0, 0, 140, 170);

        minimize.setBorder(null);
        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1045, 5, 50, 50);

        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1120, 0, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/LABEL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 170);

        veggielover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/Crispy_Veg.png"))); // NOI18N
        veggielover.setContentAreaFilled(false);
        veggielover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(veggielover);
        veggielover.setBounds(410, 170, 390, 220);

        tandooripaneer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/VegWhopper.png"))); // NOI18N
        tandooripaneer.setContentAreaFilled(false);
        tandooripaneer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(tandooripaneer);
        tandooripaneer.setBounds(790, 170, 390, 220);

        paneervagorama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/VegChilliCheeseMelt.png"))); // NOI18N
        paneervagorama.setContentAreaFilled(false);
        paneervagorama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(paneervagorama);
        paneervagorama.setBounds(10, 495, 390, 220);

        exotica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/BK_Tandoor grill.png"))); // NOI18N
        exotica.setContentAreaFilled(false);
        exotica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(exotica);
        exotica.setBounds(400, 495, 390, 210);

        countryfest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/PaneerKingMelt.png"))); // NOI18N
        countryfest.setContentAreaFilled(false);
        countryfest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(countryfest);
        countryfest.setBounds(800, 485, 390, 220);

        veggiesupreme5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/BKVeggie.png"))); // NOI18N
        veggiesupreme5.setContentAreaFilled(false);
        veggiesupreme5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(veggiesupreme5);
        veggiesupreme5.setBounds(30, 170, 390, 220);

        jButton1.setFont(new java.awt.Font("Just In The Firestorm", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("FOR NON-VEG BURGUR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(840, 830, 360, 70);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Veg Whopper");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(860, 400, 250, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" ₹ 169");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(930, 440, 110, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" ₹ 109");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 760, 110, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Veg chilli cheese melt");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 720, 250, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" ₹ 99");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(550, 760, 110, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tandoor Grill");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 720, 250, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" ₹ 199");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(940, 760, 110, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Paneer King Melt");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(870, 720, 250, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" ₹ 69");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 430, 110, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Veggie");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 390, 250, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" ₹ 99");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 430, 110, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Crisy veg");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(460, 390, 250, 30);

        menu.setFont(new java.awt.Font("Just In The Firestorm", 1, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 0, 0));
        menu.setText("back to menu");
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(410, 830, 360, 70);

        jButton2.setFont(new java.awt.Font("Just In The Firestorm", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("bill Please!");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 830, 360, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        
        try {
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(burgurs.class.getName()).log(Level.SEVERE, null, ex);
        }setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(start.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        
        try {
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(burgurs.class.getName()).log(Level.SEVERE, null, ex);
        }setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void veggieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggieActionPerformed
        if(veggie.isSelected())
        {
            try {
                ResultSet res=st.executeQuery("select * from menu where id='bv01'");
                res.next();
                String id=res.getString(1);
                String na=res.getString(2);
                String ty=res.getString(3);
                int pr=Integer.parseInt(res.getString(4));
                st.executeUpdate("insert into bill values('"+res.getString(1)+"','"+na+"','"+ty+"',"+pr+")");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {

            try {
                st.executeUpdate("delete from bill where id='bv01'");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_veggieActionPerformed

    private void crispyvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crispyvegActionPerformed
        if(crispyveg.isSelected())
        {
            try {
                ResultSet res=st.executeQuery("select * from menu where id='bv02'");
                res.next();
                String id=res.getString(1);
                String na=res.getString(2);
                String ty=res.getString(3);
                int pr=Integer.parseInt(res.getString(4));
                st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {

            try {
                st.executeUpdate("delete from bill where id='bv02'");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_crispyvegActionPerformed

    private void vegwhopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegwhopperActionPerformed
        if(vegwhopper.isSelected())
        {
            try {
                ResultSet res=st.executeQuery("select * from menu where id='bv03'");
                res.next();
                String id=res.getString(1);
                String na=res.getString(2);
                String ty=res.getString(3);
                int pr=Integer.parseInt(res.getString(4));
                st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {

            try {
                st.executeUpdate("delete from bill where id='bv03'");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_vegwhopperActionPerformed

    private void paneerkingmeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneerkingmeltActionPerformed
        if(paneerkingmelt.isSelected())
        {
            try {
                ResultSet res=st.executeQuery("select * from menu where id='bv06'");
                res.next();
                String id=res.getString(1);
                String na=res.getString(2);
                String ty=res.getString(3);
                int pr=Integer.parseInt(res.getString(4));
                st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {

            try {
                st.executeUpdate("delete from bill where id='bv06'");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_paneerkingmeltActionPerformed

    private void tandoorgrillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tandoorgrillActionPerformed
        if(tandoorgrill.isSelected())
        {
            try {
                ResultSet res=st.executeQuery("select * from menu where id='bv05'");
                res.next();
                String id=res.getString(1);
                String na=res.getString(2);
                String ty=res.getString(3);
                int pr=Integer.parseInt(res.getString(4));
                st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {

            try {
                st.executeUpdate("delete from bill where id='bv05'");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_tandoorgrillActionPerformed

    private void vegchillicheesemeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegchillicheesemeltActionPerformed
        if(vegchillicheesemelt.isSelected())
        {
            try {
                ResultSet res=st.executeQuery("select * from menu where id='bv04'");
                res.next();
                String id=res.getString(1);
                String na=res.getString(2);
                String ty=res.getString(3);
                int pr=Integer.parseInt(res.getString(4));
                st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {

            try {
                st.executeUpdate("delete from bill where id='bv04'");
            } catch (SQLException ex) {
                Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_vegchillicheesemeltActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new burgurnonveg().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

        new menu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new info().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(desserts.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(burgurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(burgurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(burgurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(burgurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new burgurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton countryfest;
    private javax.swing.JRadioButton crispyveg;
    private javax.swing.JButton exotica;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menu;
    private javax.swing.JButton minimize;
    private javax.swing.JRadioButton paneerkingmelt;
    private javax.swing.JButton paneervagorama;
    private javax.swing.JRadioButton tandoorgrill;
    private javax.swing.JButton tandooripaneer;
    private javax.swing.JRadioButton vegchillicheesemelt;
    private javax.swing.JRadioButton veggie;
    private javax.swing.JButton veggielover;
    private javax.swing.JButton veggiesupreme5;
    private javax.swing.JRadioButton vegwhopper;
    // End of variables declaration//GEN-END:variables
}
