/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzashop;
import com.placeholder.PlaceHolder;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ARUN
 */
public class info extends javax.swing.JFrame {

    Connection con;
    Statement st;
    /**
     * Creates new form info
     */
    public info() throws ClassNotFoundException {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizzashop","root","1234");
            st= con.createStatement();
            
        
        } catch (SQLException ex) {
              System.out.println("connectivity failed");
        }
        placeholder();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JButton();
        close = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        contact = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        registered = new javax.swing.JTextField();
        loginbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setUndecorated(true);
        getContentPane().setLayout(null);

        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(1045, 5, 50, 50);

        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(1120, 0, 50, 50);

        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(0, 0, 140, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/LABEL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 170);

        submit.setFont(new java.awt.Font("Death Hector", 1, 48)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 0, 255));
        submit.setText("submit");
        submit.setContentAreaFilled(false);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(290, 750, 290, 80);

        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setBorder(null);
        contact.setOpaque(false);
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        getContentPane().add(contact);
        contact.setBounds(400, 675, 400, 40);

        back.setFont(new java.awt.Font("Death Hector", 1, 48)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 255));
        back.setText("back");
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(680, 750, 270, 80);

        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(null);
        username.setOpaque(false);
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(409, 362, 380, 40);

        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);
        address.setOpaque(false);
        getContentPane().add(address);
        address.setBounds(278, 466, 650, 40);

        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(null);
        email.setOpaque(false);
        getContentPane().add(email);
        email.setBounds(400, 570, 400, 40);

        registered.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registered.setBorder(null);
        registered.setOpaque(false);
        registered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredActionPerformed(evt);
            }
        });
        registered.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registeredKeyTyped(evt);
            }
        });
        getContentPane().add(registered);
        registered.setBounds(400, 215, 400, 40);

        loginbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/loginbg.png"))); // NOI18N
        loginbg.setText("jLabel2");
        getContentPane().add(loginbg);
        loginbg.setBounds(0, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(start.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        try {
            setVisible(false);
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(membership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        try {
            setVisible(false);
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(membership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       if(!username.getText().equals("Enter your name "))
       {
        String name=username.getText();
        String addr=address.getText();
        String em=email.getText();
        String number=contact.getText();
       
           try {
               new bill(name,addr,em,number,0).setVisible(true);
               setVisible(false);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(info.class.getName()).log(Level.SEVERE, null, ex);
           

      
       
           }}
       else{
           try {
               
               ResultSet res=st.executeQuery("select * from member where contact='"+registered.getText()+"'");
               res.next();
               String name=res.getString(1);
               String addr=res.getString(2);
               String em=res.getString(3);
               String number=res.getString(4);
               try {
                   setVisible(false);
                   new bill(name,addr,em,number,10).setVisible(true);
               } catch (ClassNotFoundException ex) {
                   Logger.getLogger(info.class.getName()).log(Level.SEVERE, null, ex);
               }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"you are not registered member","ERROR",JOptionPane.ERROR_MESSAGE);
               Logger.getLogger(info.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
            
            

                
        
    }//GEN-LAST:event_submitActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char s= evt.getKeyChar();
        if(!((s==KeyEvent.VK_DELETE)||Character.isDigit(s)||(s==KeyEvent.VK_BACK_SPACE)))
        {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_contactKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            setVisible(false);
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(membership.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyTyped

    private void registeredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredActionPerformed

    private void registeredKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registeredKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_registeredKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new info().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(info.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginbg;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField registered;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
 private void placeholder()  {
        
        PlaceHolder name= new PlaceHolder(username,"Enter your name ");
        PlaceHolder add= new PlaceHolder(address,"Enter your address ");
        PlaceHolder cont= new PlaceHolder(contact,"Enter your mobile no.");
        PlaceHolder em= new PlaceHolder(email,"Enter your email");
        PlaceHolder co= new PlaceHolder(registered,"Enter your registered contact no.");
        Font fo=new Font("Calibri",1, 24);
        username.setFont(fo);
        address.setFont(fo);
        contact.setFont(fo);
        email.setFont(fo);
        registered.setFont(fo);
        
        
        
        
        
        
            }
     private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pizzashop/img/icon.png")));
    }
}



