
package pizzashop;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
/**
 *
 * @author ARUN
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public menu() {
        initComponents();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pizzamenu = new javax.swing.JButton();
        burgermenu = new javax.swing.JButton();
        garlicmenu = new javax.swing.JButton();
        dessertmenu = new javax.swing.JButton();
        menushow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(null);

        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(0, 0, 140, 170);
        home.getAccessibleContext().setAccessibleName("home");

        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1120, 0, 50, 50);

        minimize.setBorder(null);
        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1045, 5, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/LABEL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 170);

        pizzamenu.setBackground(new java.awt.Color(255, 153, 0));
        pizzamenu.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        pizzamenu.setForeground(new java.awt.Color(255, 0, 0));
        pizzamenu.setText("PIZZA");
        pizzamenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        pizzamenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pizzamenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pizzamenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pizzamenuMouseExited(evt);
            }
        });
        pizzamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzamenuActionPerformed(evt);
            }
        });
        jPanel1.add(pizzamenu);
        pizzamenu.setBounds(0, 180, 260, 60);

        burgermenu.setBackground(new java.awt.Color(255, 153, 0));
        burgermenu.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        burgermenu.setForeground(new java.awt.Color(255, 0, 0));
        burgermenu.setText("BURGERS");
        burgermenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        burgermenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        burgermenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                burgermenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                burgermenuMouseExited(evt);
            }
        });
        burgermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgermenuActionPerformed(evt);
            }
        });
        jPanel1.add(burgermenu);
        burgermenu.setBounds(260, 180, 320, 60);

        garlicmenu.setBackground(new java.awt.Color(255, 153, 0));
        garlicmenu.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        garlicmenu.setForeground(new java.awt.Color(255, 0, 0));
        garlicmenu.setText("SIDES");
        garlicmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        garlicmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        garlicmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                garlicmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                garlicmenuMouseExited(evt);
            }
        });
        garlicmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garlicmenuActionPerformed(evt);
            }
        });
        jPanel1.add(garlicmenu);
        garlicmenu.setBounds(580, 180, 280, 60);

        dessertmenu.setBackground(new java.awt.Color(255, 153, 0));
        dessertmenu.setFont(new java.awt.Font("Death Hector", 2, 24)); // NOI18N
        dessertmenu.setForeground(new java.awt.Color(255, 0, 0));
        dessertmenu.setText("DESSERTS");
        dessertmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 255, 0), null, new java.awt.Color(255, 0, 0)));
        dessertmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dessertmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dessertmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dessertmenuMouseExited(evt);
            }
        });
        dessertmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertmenuActionPerformed(evt);
            }
        });
        jPanel1.add(dessertmenu);
        dessertmenu.setBounds(860, 180, 340, 60);

        menushow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/menu.png"))); // NOI18N
        jPanel1.add(menushow);
        menushow.setBounds(100, 250, 1000, 630);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       
        try {
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(start.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       
        try {
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false); 
    }//GEN-LAST:event_homeActionPerformed

    private void pizzamenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzamenuMouseEntered
      
        pizzamenu.setBackground(new Color(255,255,0));
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/bg1.jpg"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_pizzamenuMouseEntered

    private void pizzamenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzamenuMouseExited
        pizzamenu.setBackground(new Color(255,153,0));       
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/menu.png"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_pizzamenuMouseExited

    private void pizzamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzamenuActionPerformed
       
        try {
            new pizzaveg().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
         setVisible(false);
    }//GEN-LAST:event_pizzamenuActionPerformed

    private void burgermenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgermenuMouseEntered
        burgermenu.setBackground(new Color(255,255,0));   
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/bg9.jpg"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_burgermenuMouseEntered

    private void burgermenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgermenuMouseExited
        burgermenu.setBackground(new Color(255,153,0)); 
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/menu.png"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_burgermenuMouseExited

    private void garlicmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_garlicmenuMouseEntered
        garlicmenu.setBackground(new Color(255,255,0));     
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/bg6.jpg"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_garlicmenuMouseEntered

    private void garlicmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_garlicmenuMouseExited
        garlicmenu.setBackground(new Color(255,153,0));        
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/menu.png"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_garlicmenuMouseExited

    private void dessertmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessertmenuMouseEntered
        dessertmenu.setBackground(new Color(255,255,0));     
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/bg7.jpg"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_dessertmenuMouseEntered

    private void dessertmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessertmenuMouseExited
        dessertmenu.setBackground(new Color(255,153,0));        
        ImageIcon ii=new ImageIcon(getClass().getResource("/pizzashop/img/menu.png"));
                            menushow.setIcon(ii);
    }//GEN-LAST:event_dessertmenuMouseExited

    private void garlicmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garlicmenuActionPerformed
        try {
            new sides().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
         setVisible(false);
    }//GEN-LAST:event_garlicmenuActionPerformed

    private void burgermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgermenuActionPerformed
        new burgurs().setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_burgermenuActionPerformed

    private void dessertmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertmenuActionPerformed
        try {
            new desserts().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
         setVisible(false);
    }//GEN-LAST:event_dessertmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton burgermenu;
    private javax.swing.JButton close;
    private javax.swing.JButton dessertmenu;
    private javax.swing.JButton garlicmenu;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menushow;
    private javax.swing.JButton minimize;
    private javax.swing.JButton pizzamenu;
    // End of variables declaration//GEN-END:variables
 private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pizzashop/img/icon.png")));
    }
}

