/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzashop;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ARUN
 */
public class sides extends javax.swing.JFrame {

    Connection con;
    Statement st;
    /**
     * Creates new form garlicbread
     */
    public sides() throws ClassNotFoundException {
        initComponents();
        seticon();
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pizzashop","root","1234");
            st= con.createStatement();
            
        
        } catch (SQLException ex) {
              System.out.println("connectivity failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cheesegarlicbread = new javax.swing.JRadioButton();
        garlicbreadstix = new javax.swing.JRadioButton();
        nonvegpocket = new javax.swing.JRadioButton();
        exoticagarlicbread = new javax.swing.JRadioButton();
        garlicbreadspicysupreme = new javax.swing.JRadioButton();
        vegpockets = new javax.swing.JRadioButton();
        veggielover = new javax.swing.JButton();
        tandooripaneer = new javax.swing.JButton();
        paneervagorama = new javax.swing.JButton();
        exotica = new javax.swing.JButton();
        countryfest = new javax.swing.JButton();
        veggiesupreme5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        home.setBorder(null);
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(0, 0, 140, 170);

        minimize.setBorder(null);
        minimize.setBorderPainted(false);
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(1045, 5, 50, 50);

        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1120, 0, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/LABEL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 170);

        cheesegarlicbread.setBorder(null);
        cheesegarlicbread.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cheesegarlicbread.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cheesegarlicbread.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cheesegarlicbread.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        cheesegarlicbread.setOpaque(false);
        cheesegarlicbread.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        cheesegarlicbread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesegarlicbreadActionPerformed(evt);
            }
        });
        jPanel1.add(cheesegarlicbread);
        cheesegarlicbread.setBounds(60, 175, 350, 190);

        garlicbreadstix.setBorder(null);
        garlicbreadstix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        garlicbreadstix.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        garlicbreadstix.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        garlicbreadstix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        garlicbreadstix.setOpaque(false);
        garlicbreadstix.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        garlicbreadstix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garlicbreadstixActionPerformed(evt);
            }
        });
        jPanel1.add(garlicbreadstix);
        garlicbreadstix.setBounds(440, 180, 350, 190);

        nonvegpocket.setBorder(null);
        nonvegpocket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nonvegpocket.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nonvegpocket.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        nonvegpocket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        nonvegpocket.setOpaque(false);
        nonvegpocket.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        nonvegpocket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonvegpocketActionPerformed(evt);
            }
        });
        jPanel1.add(nonvegpocket);
        nonvegpocket.setBounds(50, 510, 350, 190);

        exoticagarlicbread.setBorder(null);
        exoticagarlicbread.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exoticagarlicbread.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exoticagarlicbread.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        exoticagarlicbread.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        exoticagarlicbread.setOpaque(false);
        exoticagarlicbread.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        exoticagarlicbread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exoticagarlicbreadActionPerformed(evt);
            }
        });
        jPanel1.add(exoticagarlicbread);
        exoticagarlicbread.setBounds(820, 180, 350, 190);

        garlicbreadspicysupreme.setBorder(null);
        garlicbreadspicysupreme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        garlicbreadspicysupreme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        garlicbreadspicysupreme.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        garlicbreadspicysupreme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        garlicbreadspicysupreme.setOpaque(false);
        garlicbreadspicysupreme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        garlicbreadspicysupreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garlicbreadspicysupremeActionPerformed(evt);
            }
        });
        jPanel1.add(garlicbreadspicysupreme);
        garlicbreadspicysupreme.setBounds(830, 510, 350, 190);

        vegpockets.setBorder(null);
        vegpockets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vegpockets.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vegpockets.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        vegpockets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/9.png"))); // NOI18N
        vegpockets.setOpaque(false);
        vegpockets.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/green-tick.png"))); // NOI18N
        vegpockets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegpocketsActionPerformed(evt);
            }
        });
        jPanel1.add(vegpockets);
        vegpockets.setBounds(430, 510, 350, 190);

        veggielover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/garlic bread stix.png"))); // NOI18N
        veggielover.setBorderPainted(false);
        veggielover.setContentAreaFilled(false);
        veggielover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(veggielover);
        veggielover.setBounds(410, 170, 390, 195);

        tandooripaneer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/exotica garlic bread.png"))); // NOI18N
        tandooripaneer.setBorderPainted(false);
        tandooripaneer.setContentAreaFilled(false);
        tandooripaneer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(tandooripaneer);
        tandooripaneer.setBounds(790, 170, 390, 195);

        paneervagorama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/nin-veg pocket.png"))); // NOI18N
        paneervagorama.setBorderPainted(false);
        paneervagorama.setContentAreaFilled(false);
        paneervagorama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(paneervagorama);
        paneervagorama.setBounds(10, 500, 390, 195);

        exotica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/veg pocket.png"))); // NOI18N
        exotica.setBorderPainted(false);
        exotica.setContentAreaFilled(false);
        exotica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(exotica);
        exotica.setBounds(400, 500, 390, 195);

        countryfest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/garlicbreadspicysupreme.png"))); // NOI18N
        countryfest.setBorderPainted(false);
        countryfest.setContentAreaFilled(false);
        countryfest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(countryfest);
        countryfest.setBounds(800, 500, 390, 195);

        veggiesupreme5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzashop/img/cheese garlic bread.png"))); // NOI18N
        veggiesupreme5.setBorderPainted(false);
        veggiesupreme5.setContentAreaFilled(false);
        veggiesupreme5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(veggiesupreme5);
        veggiesupreme5.setBounds(30, 170, 390, 195);

        jButton1.setFont(new java.awt.Font("Just In The Firestorm", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("back to menu");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(840, 830, 360, 70);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Garlic Bread Spicy Supreme");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(820, 710, 350, 40);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("₹99");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(870, 750, 270, 40);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Garlic Bread Stix");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 380, 270, 40);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Exotica Garlic Bread");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(870, 380, 270, 40);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Non-Veg Pockets");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 710, 270, 40);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Veg Pockets");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 710, 270, 40);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cheese Garlic Bread");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 380, 270, 40);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("₹99");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 420, 270, 40);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("₹85");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 420, 270, 40);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("₹125");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(870, 420, 270, 40);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("₹89");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 750, 270, 40);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("₹69");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(470, 750, 270, 40);

        jButton2.setFont(new java.awt.Font("Just In The Firestorm", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("bill Please!");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 830, 360, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        
        try {
            new start().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sides.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(start.ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       
        try {
            new start().setVisible(true);
            setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sides.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        new menu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            new info().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(desserts.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cheesegarlicbreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheesegarlicbreadActionPerformed
        if(cheesegarlicbread.isSelected())
            {
                try {
                    ResultSet res=st.executeQuery("select * from menu where id='s01'");
                    res.next();
                    String id=res.getString(1);
                    String na=res.getString(2);
                    String ty=res.getString(3);
                    int pr=Integer.parseInt(res.getString(4));
                    st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                try {
                    st.executeUpdate("delete from bill where id='s01'");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
 
    }//GEN-LAST:event_cheesegarlicbreadActionPerformed

    private void garlicbreadstixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garlicbreadstixActionPerformed
                if(garlicbreadstix.isSelected())
            {
                try {
                    ResultSet res=st.executeQuery("select * from menu where id='s02'");
                    res.next();
                    String id=res.getString(1);
                    String na=res.getString(2);
                    String ty=res.getString(3);
                    int pr=Integer.parseInt(res.getString(4));
                    st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                try {
                    st.executeUpdate("delete from bill where id='s02'");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
 
    }//GEN-LAST:event_garlicbreadstixActionPerformed

    private void exoticagarlicbreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exoticagarlicbreadActionPerformed
        // TODO add your handling code here:
        if(exoticagarlicbread.isSelected())
            {
                try {
                    ResultSet res=st.executeQuery("select * from menu where id='s03'");
                    res.next();
                    String id=res.getString(1);
                    String na=res.getString(2);
                    String ty=res.getString(3);
                    int pr=Integer.parseInt(res.getString(4));
                    st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                try {
                    st.executeUpdate("delete from bill where id='s03'");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
 
    }//GEN-LAST:event_exoticagarlicbreadActionPerformed

    private void nonvegpocketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonvegpocketActionPerformed
        if(nonvegpocket.isSelected())
            {
                try {
                    ResultSet res=st.executeQuery("select * from menu where id='s04'");
                    res.next();
                    String id=res.getString(1);
                    String na=res.getString(2);
                    String ty=res.getString(3);
                    int pr=Integer.parseInt(res.getString(4));
                    st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                try {
                    st.executeUpdate("delete from bill where id='s04'");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_nonvegpocketActionPerformed

    private void vegpocketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegpocketsActionPerformed
        if(vegpockets.isSelected())
            {
                try {
                    ResultSet res=st.executeQuery("select * from menu where id='s05'");
                    res.next();
                    String id=res.getString(1);
                    String na=res.getString(2);
                    String ty=res.getString(3);
                    int pr=Integer.parseInt(res.getString(4));
                    st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                try {
                    st.executeUpdate("delete from bill where id='s05'");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
         // TODO add your handling code here:
    }//GEN-LAST:event_vegpocketsActionPerformed

    private void garlicbreadspicysupremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garlicbreadspicysupremeActionPerformed
        if(garlicbreadspicysupreme.isSelected())
            {
                try {
                    ResultSet res=st.executeQuery("select * from menu where id='s06'");
                    res.next();
                    String id=res.getString(1);
                    String na=res.getString(2);
                    String ty=res.getString(3);
                    int pr=Integer.parseInt(res.getString(4));
                    st.executeUpdate("insert into bill values('"+id+"','"+na+"','"+ty+"',"+pr+")");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                try {
                    st.executeUpdate("delete from bill where id='s06'");
                } catch (SQLException ex) {
                    Logger.getLogger(pizzaveg.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
         // TODO add your handling code here:
    }//GEN-LAST:event_garlicbreadspicysupremeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new sides().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(sides.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cheesegarlicbread;
    private javax.swing.JButton close;
    private javax.swing.JButton countryfest;
    private javax.swing.JButton exotica;
    private javax.swing.JRadioButton exoticagarlicbread;
    private javax.swing.JRadioButton garlicbreadspicysupreme;
    private javax.swing.JRadioButton garlicbreadstix;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimize;
    private javax.swing.JRadioButton nonvegpocket;
    private javax.swing.JButton paneervagorama;
    private javax.swing.JButton tandooripaneer;
    private javax.swing.JButton veggielover;
    private javax.swing.JButton veggiesupreme5;
    private javax.swing.JRadioButton vegpockets;
    // End of variables declaration//GEN-END:variables
 private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pizzashop/img/icon.png")));
    }
}
